# Generated by Django 4.0.6 on 2022-07-28 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advuser',
            old_name='is_acitvated',
            new_name='is_activated',
        ),
    ]
